rawArray = [
  [
    "Unique Id",
    "Type",
    "Make",
    "Model",
    "Year",
    "Color",
    "Condition",
    "Case",
    "Price",
    "Description",
    "Picture1",
    "Picture2",
    "Picture3",
    "Picture4",
    "Picture5",
    "Picture6",
    "Dealer Key",
    "Dealer Notes",
    "Offsite Link #1 Label",
    "Offsite Link #1 Url",
    "Offsite Link #2 Label",
    "Offsite Link #2 Url",
  ],
  [
    "STR-1989-SB",
    "Guitar",
    "Fender",
    "Stratocaster",
    "1989",
    "Sunburst",
    "Good",
    "Hard",
    "999.99",
    "Classic 1989 Fender Stratocaster in sunburst finish. Some wear on the back but overall in good condition. Comes with a hard case.",
    "https://example.com/STR-1989-SB_1.jpg",
    "https://example.com/STR-1989-SB_2.jpg",
    "https://example.com/STR-1989-SB_3.jpg",
    "",
    "",
    "",
    "DK-STR-1989-SB",
    "Some dings on the back, otherwise great.",
    "Spec Sheet",
    "https://example.com/STR-1989-SB_spec.pdf",
    "User Reviews",
    "https://example.com/STR-1989-SB_reviews.html",
  ],
  [
    "LP-2005-SB",
    "Guitar",
    "Gibson",
    "Les Paul",
    "2005",
    "Sunburst",
    "Fair",
    "Hard",
    "599.99",
    "2005 Gibson Les Paul in sunburst finish. Some dents and scratches but still fully functional. Comes with a hard case.",
    "https://example.com/LP-2005-SB_1.jpg",
    "https://example.com/LP-2005-SB_2.jpg",
    "https://example.com/LP-2005-SB_3.jpg",
    "",
    "",
    "",
    "DK-LP-2005-SB",
    "Dents and scratches, fully functional.",
    "Spec Sheet",
    "https://example.com/LP-2005-SB_spec.pdf",
    "User Reviews",
    "https://example.com/LP-2005-SB_reviews.html",
  ],
  [
    "P-2000-SB",
    "Guitar",
    "Fender",
    "Precision",
    "2000",
    "Sunburst",
    "Good",
    "Hard",
    "799.99",
    "2000 Fender Precision bass in sunburst finish. Some wear on the back but overall in good condition. Comes with a hard case.",
    "https://example.com/P-2000-SB_1.jpg",
    "https://example.com/P-2000-SB_2.jpg",
    "https://example.com/P-2000-SB_3.jpg",
    "",
    "",
    "",
    "DK-P-2000-SB",
    "Some wear on the back, otherwise good.",
    "Spec Sheet",
    "https://example.com/P-2000-SB_spec.pdf",
    "User Reviews",
    "https://example.com/P-2000-SB_reviews.html",
  ],
  [
    "SG-2007-CH",
    "Guitar",
    "Gibson",
    "SG",
    "2007",
    "Cherry",
    "Good",
    "Hard",
    "799.99",
    "2007 Gibson SG in cherry finish. Some wear on the back but overall in good condition. Comes with a hard case.",
    "https://example.com/SG-2007-CH_1.jpg",
    "https://example.com/SG-2007-CH_2.jpg",
    "https://example.com/SG-2007-CH_3.jpg",
    "",
    "",
    "",
    "DK-SG-2007-CH",
    "Some wear on the back, otherwise good.",
    "Spec Sheet",
    "https://example.com/SG-2007-CH_spec.pdf",
    "User Reviews",
    "https://example.com/SG-2007-CH_reviews.html",
  ],
  [""],
  [""],
];


